### ISSUE TITLE
Auto append LiveReload javascript code

### ISSUE THREAD

**Issue by jsncrdnl** [taggon/livereload#10]
Wouldn't it be possible to add a setting toggle for this plugin ?
This might automatically append the live reload js code to a newly opened preview tab (so that we don't have to modify our source html file) ? (just like Brackets is doing for it's live preview)

**Comment by taggon** [comment]
If you don't want to modify your html file, [Chrome LiveReload extension](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en) can be a good option.

It is hard to make my package provide the feature you want because Atom doesn't have any default package for previewing html files. I don't know what packages I should support.
