### ISSUE TITLE
Livereload crashes atom editor

### ISSUE THREAD

**Issue by harryi3t** [taggon/livereload#33]
After installing livereload I have not been able to use it.
As soon as I toggle the option my atom hangs and after few seconds I get this screen.
![image](https://cloud.githubusercontent.com/assets/5207331/14231218/a28060c6-f998-11e5-97c8-0ac8c7b15f22.png)

I cannot click on `show stack trace` as the editor itself has crashed. I tried multiple times, same result.

If you want any more details please let me know.

**Comment by taggon** [comment]
I think this is the same issue:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

In a few words, execute the following command:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Someone explained why:
> The system has a limit to how many files can be watched by a user. You can run out of watches pretty quickly if you have Grunt running with other programs like Dropbox. This command increases the maximum amount of watches a user can have.
Benjamin Manns the Sep 3 '13 at 19:28

**Comment by harryi3t** [comment]
Oh that make sense, I have node_modules and bower_components directories. So there are so many files to watch.
Thanks for the solution but is there any way I can instruct liveReload to ignore for these directories?

**Comment by cwilli34** [comment]
I had to do a npm dedupe and add fs.inotify.max_user_watches=524288 to /etc/sysctl.d/100-manjaro.conf, but of course that is because I am using Manjaro (Arch) linux.  For other Arch distros this might be /etc/systcl.d/99-systcl.config, or  /usr/lib/sysctl.d/50-default.conf.  That is also explained in the comments of http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc 

Worked good though.  Thanks for this!

**Comment by sukrosono** [comment]
@harryi3t The plugin have setting, Add it on additional exclusion. IG if the issue not valid it should be closed

**Comment by harryi3t** [comment]
@brutalcrozt Thanks. Didn't know there was a setting for it.
